// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw3NLuKnE4_cGvxxOwglrgMi-mIOMTX8Q',
    appId: '1:472559707246:web:10dcc783dc248cd807327f',
    messagingSenderId: '472559707246',
    projectId: 'expo-booking-e6518',
    authDomain: 'expo-booking-e6518.firebaseapp.com',
    storageBucket: 'expo-booking-e6518.firebasestorage.app',
    measurementId: 'G-BG0Y2G6SZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjL5R10Xl5ZAnoTv6LN-a0Vc4gxNUtQrc',
    appId: '1:472559707246:android:4d6a3900404acb1807327f',
    messagingSenderId: '472559707246',
    projectId: 'expo-booking-e6518',
    storageBucket: 'expo-booking-e6518.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7mwYvaZRnN-LGjJe3JFCGDCp6M1eCnvQ',
    appId: '1:472559707246:ios:30c6640616375d9707327f',
    messagingSenderId: '472559707246',
    projectId: 'expo-booking-e6518',
    storageBucket: 'expo-booking-e6518.firebasestorage.app',
    iosBundleId: 'com.example.expoManagerBoothNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7mwYvaZRnN-LGjJe3JFCGDCp6M1eCnvQ',
    appId: '1:472559707246:ios:30c6640616375d9707327f',
    messagingSenderId: '472559707246',
    projectId: 'expo-booking-e6518',
    storageBucket: 'expo-booking-e6518.firebasestorage.app',
    iosBundleId: 'com.example.expoManagerBoothNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw3NLuKnE4_cGvxxOwglrgMi-mIOMTX8Q',
    appId: '1:472559707246:web:8593294fdf9d5ccb07327f',
    messagingSenderId: '472559707246',
    projectId: 'expo-booking-e6518',
    authDomain: 'expo-booking-e6518.firebaseapp.com',
    storageBucket: 'expo-booking-e6518.firebasestorage.app',
    measurementId: 'G-EDLEXDE647',
  );
}
